{
  "openapi": "3.0.1",
  "servers": [
    {
      "description": "Production",
      "url": "https://products.izettle.com",
      "variables": {}
    }
  ],
  "info": {
    "description": "The Product Library API is used for managing merchant's product information and product images.",
    "title": "Product Library API",
    "version": "1.0.0",
    "x-apisguru-categories": [
      "ecommerce"
    ],
    "x-logo": {
      "url": "https://cdn.izettle.com/favicons/favicon-32x32.png"
    },
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://products.izettle.com/openapi.json",
        "version": "3.0"
      }
    ],
    "x-providerName": "izettle.com",
    "x-serviceName": "products"
  },
  "paths": {
    "/organizations/id/categories/v2": {
      "get": {
        "operationId": "getproducttypes",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve all categories",
        "tags": [
          "categories"
        ]
      },
      "post": {
        "operationId": "createcategories-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Create a new category",
        "tags": [
          "categories"
        ]
      }
    },
    "/organizations/orderid/categories/v2/sku": {
      "delete": {
        "operationId": "deletecategory",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Delete a category",
        "tags": [
          "categories"
        ]
      },
      "patch": {
        "operationId": "renamecategory",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Rename a category",
        "tags": [
          "categories"
        ]
      }
    },
    "/organizations/id/discounts": {
      "get": {
        "operationId": "getalldiscounts-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve all discounts",
        "tags": [
          "discounts"
        ]
      },
      "post": {
        "description": "Creates a single discount entity. The location of the newly created discount will be available in the successful response as a HttpHeaders.LOCATION header",
        "operationId": "creatediscount",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Create a discount",
        "tags": [
          "discounts"
        ]
      }
    },
    "/organizations/userid/discounts/id": {
      "delete": {
        "operationId": "deletediscount-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Delete a single discount ",
        "tags": [
          "discounts"
        ]
      },
      "get": {
        "description": "Get the full discount with the provided UUID. The method supports conditional GET through providing a HttpHeaders.IF_NONE_MATCH header. If the conditional prerequisite is fullfilled, the full discount is returned: otherwise a 304 not modified will be returned with an empty body.",
        "operationId": "getdiscount",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve a single discount",
        "tags": [
          "discounts"
        ]
      },
      "put": {
        "description": "Updates a discount entity using JSON merge patch (https://tools.ietf.org/html/rfc7386). This means that only included fields will be changed: null values removes the field on the target entity, and other values updates the field. Conditional updates are supported through the HttpHeaders.IF_MATCH header. If the conditional prerequisite is fullfilled, the discount is updated: otherwise a 412 precondition failed will be returned with an empty body.",
        "operationId": "updatediscount",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Update a single discount",
        "tags": [
          "discounts"
        ]
      }
    },
    "/organizations/orderid/images": {
      "get": {
        "description": "Retrieves all library items images used by the organization, sorted by updated date",
        "operationId": "getallimageurls-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve all library item images",
        "tags": [
          "images"
        ]
      }
    },
    "/organizations/sku/import/status": {
      "get": {
        "operationId": "getlatestimportstatus",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get status for latest import",
        "tags": [
          "import"
        ]
      }
    },
    "/organizations/orderid/import/status/orderid": {
      "get": {
        "operationId": "getstatusbyud",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get status for an import",
        "tags": [
          "import"
        ]
      }
    },
    "/organizations/sku/import/v2": {
      "post": {
        "operationId": "importlibraryv2-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Import library items",
        "tags": [
          "import"
        ]
      }
    },
    "/organizations/orderid/library": {
      "get": {
        "description": "Will return the entire library for the authenticated user. If size of the library exceeds server preferences (normally 500) or the value of the optional limit parameter, the result will be paginated. Paginated responses return a Link header, indicating the next URI to fetch. The resulting header value will look something like:\n\n<https://products.izettle.com/organizations/self/library?limit=X&offset=Y>; rel=\"next\"\n\nwhere limit is number of items in response, and offs[...]",
        "operationId": "getlibrary",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve the entire library",
        "tags": [
          "library"
        ]
      }
    },
    "/organizations/sku/products": {
      "delete": {
        "operationId": "deleteproducts-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Delete a list of products",
        "tags": [
          "products"
        ]
      },
      "get": {
        "operationId": "getallproductsinpos-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve all products visible in POS",
        "tags": [
          "products"
        ]
      },
      "post": {
        "operationId": "createproduct-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Create a new product",
        "tags": [
          "products"
        ]
      }
    },
    "/organizations/id/products/online/slug": {
      "post": {
        "description": "Creates a unique slug (identifier) for a product. The slug is used to create a product URL",
        "operationId": "createproductslug-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Create a product identifier",
        "tags": [
          "products/online"
        ]
      }
    },
    "/organizations/paymentid/products/options": {
      "get": {
        "operationId": "getalloptions",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve an aggregate of active Options in the library",
        "tags": [
          "products"
        ]
      }
    },
    "/organizations/sku/products/v2": {
      "get": {
        "operationId": "getallproductsv2-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve all products visible in POS – v2",
        "tags": [
          "products"
        ]
      }
    },
    "/organizations/userid/products/v2/count": {
      "get": {
        "operationId": "countallproducts-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve the count of existing products",
        "tags": [
          "products"
        ]
      }
    },
    "/organizations/userid/products/v2/orderid": {
      "put": {
        "description": "Updates a product entity using JSON merge patch (https://tools.ietf.org/html/rfc7386). This means that only included fields will be changed: null values removes the field on the target entity, and other values updates the field. Conditional updates are supported through the HttpHeaders.IF_MATCH header. If the conditional prerequisite is fullfilled, the product is updated: otherwise a 412 (precondition failed) will be returned with an empty body.",
        "operationId": "updateproduct",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Update a single product",
        "tags": [
          "products"
        ]
      }
    },
    "/organizations/paymentid/products/userid": {
      "delete": {
        "operationId": "deleteproduct-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Delete a single product",
        "tags": [
          "products"
        ]
      },
      "get": {
        "description": "Get the full product with the provided UUID. The method supports conditional GET through providing a HttpHeaders.IF_NONE_MATCH header. If the conditional prerequisite is fullfilled, the full product is returned, otherwise a 304 not modified will be returned with an empty body.",
        "operationId": "getproduct-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Retrieve a single product",
        "tags": [
          "products"
        ]
      }
    },
    "/v1/taxes": {
      "get": {
        "operationId": "gettaxrates",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get all available tax rates",
        "tags": [
          "taxes"
        ]
      },
      "post": {
        "operationId": "createtaxrates-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Create new tax rates",
        "tags": [
          "taxes"
        ]
      }
    },
    "/v1/taxes/count": {
      "get": {
        "operationId": "getproductcountforalltaxes-v2",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get all tax rates and a count of products associated with each",
        "tags": [
          "taxes"
        ]
      }
    },
    "/v1/taxes/settings": {
      "get": {
        "operationId": "gettaxsettings",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get the organization tax settings ",
        "tags": [
          "taxes"
        ]
      },
      "put": {
        "operationId": "settaxationmode-v2",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Update the organization tax settings",
        "tags": [
          "taxes"
        ]
      }
    },
    "/v1/taxes/userid": {
      "delete": {
        "operationId": "deletetaxrate",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Delete a single tax rate",
        "tags": [
          "taxes"
        ]
      },
      "get": {
        "operationId": "gettaxrate",
        "security": [
          {
            "ZettleOauth": [
              "READ:PRODUCT"
            ]
          }
        ],
        "summary": "Get a single tax rate",
        "tags": [
          "taxes"
        ]
      },
      "put": {
        "operationId": "updatetaxrate",
        "security": [
          {
            "ZettleOauth": [
              "WRITE:PRODUCT"
            ]
          }
        ],
        "summary": "Update a single tax rate",
        "tags": [
          "taxes"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ZettleOauth": {
        "description": "For more information about authorization API visit: https://developer.zettle.com/docs/api/oauth/overview",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://oauth.zettle.com/authorize",
            "scopes": {
              "READ:PRODUCT": "Access to read product library data",
              "WRITE:PRODUCT": "Access to write product library data"
            },
            "tokenUrl": "https://oauth.zettle.com/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}