{
  "openapi": "3.0.0",
  "servers": [
    {
      "description": "Xero Payroll AU API",
      "url": "https://api.xero.com/payroll.xro/1.0"
    }
  ],
  "info": {
    "contact": {
      "email": "api@xero.com",
      "name": "Xero Platform Team",
      "url": "https://developer.xero.com",
      "x-twitter": "XeroAPI"
    },
    "description": "This is the Xero Payroll API for orgs in Australia region.",
    "license": {
      "name": "MIT",
      "url": "https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE"
    },
    "termsOfService": "https://developer.xero.com/xero-developer-platform-terms-conditions/",
    "title": "Xero Payroll AU API",
    "version": "2.9.4",
    "x-apisguru-categories": [
      "financial"
    ],
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero-payroll-au.yaml",
        "version": "3.0"
      }
    ],
    "x-providerName": "xero.com",
    "x-serviceName": "xero-payroll-au"
  },
  "tags": [
    {
      "description": "Operations available to regular developers",
      "name": "PayrollAu"
    }
  ],
  "paths": {
    "/carts/{id}": {
      "get": {
        "operationId": "getpayruns",
        "security": [
          {
            "OAuth2": [
              "payroll.payruns.read"
            ]
          }
        ],
        "summary": "Retrieves pay runs",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "createpayrun",
        "security": [
          {
            "OAuth2": [
              "payroll.payruns"
            ]
          }
        ],
        "summary": "Creates a pay run",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuProblem": true
      }
    },
    "/employees/userid": {
      "get": {
        "operationId": "getemployee-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.employees.read"
            ]
          }
        ],
        "summary": "Retrieves an employee's detail by unique employee id",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "description": "Update properties on a single employee",
        "operationId": "updateemployee",
        "security": [
          {
            "OAuth2": [
              "payroll.employees"
            ]
          }
        ],
        "summary": "Updates an employee's detail",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/profiles/{id}": {
      "get": {
        "operationId": "getleaveapplications-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.leaveapplications.read"
            ]
          }
        ],
        "summary": "Retrieves leave applications",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "createleaveapplication",
        "security": [
          {
            "OAuth2": [
              "payroll.leaveapplications"
            ]
          }
        ],
        "summary": "Creates a leave application",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuProblem": true
      }
    },
    "/leaveapplications/paymentid": {
      "get": {
        "operationId": "getleaveapplication",
        "security": [
          {
            "OAuth2": [
              "payroll.leaveapplications.read"
            ]
          }
        ],
        "summary": "Retrieves a leave application by a unique leave application id",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "updateleaveapplication-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.leaveapplications"
            ]
          }
        ],
        "summary": "Updates a specific leave application",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/shipments/{id}": {
      "get": {
        "operationId": "getpayrollcalendars-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.payrollcalendars.read"
            ]
          }
        ],
        "summary": "Retrieves payroll calendars",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "createpayrollcalendar",
        "security": [
          {
            "OAuth2": [
              "payroll.payrollcalendars"
            ]
          }
        ],
        "summary": "Creates a Payroll Calendar",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuProblem": true
      }
    },
    "/payruns/paymentid": {
      "get": {
        "operationId": "getpayrun",
        "security": [
          {
            "OAuth2": [
              "payroll.payruns.read"
            ]
          }
        ],
        "summary": "Retrieves a pay run by using a unique pay run id",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "description": "Update properties on a single PayRun",
        "operationId": "updatepayrun",
        "security": [
          {
            "OAuth2": [
              "payroll.payruns"
            ]
          }
        ],
        "summary": "Updates a pay run",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/payrollcalendars/paymentid": {
      "get": {
        "operationId": "getpayrollcalendar",
        "security": [
          {
            "OAuth2": [
              "payroll.payrollcalendars.read"
            ]
          }
        ],
        "summary": "Retrieves payroll calendar by using a unique payroll calendar ID",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/payslip/userid": {
      "get": {
        "operationId": "getpayslip",
        "security": [
          {
            "OAuth2": [
              "payroll.payslip.read"
            ]
          }
        ],
        "summary": "Retrieves for a payslip by a unique payslip id",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "description": "Update lines on a single payslips",
        "operationId": "updatepayslip-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.payslip"
            ]
          }
        ],
        "summary": "Updates a payslip",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuError": true
      }
    },
    "/payments/{id}": {
      "get": {
        "operationId": "getsettings-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.settings.read"
            ]
          }
        ],
        "summary": "Retrieves payroll settings",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/orders/{id}": {
      "get": {
        "operationId": "getsuperfunds-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.superfunds.read"
            ]
          }
        ],
        "summary": "Retrieves superfunds",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "createsuperfund-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.superfunds"
            ]
          }
        ],
        "summary": "Creates a superfund",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuProblem": true
      }
    },
    "/superfunds/paymentid": {
      "get": {
        "operationId": "getsuperfund-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.superfunds.read"
            ]
          }
        ],
        "summary": "Retrieves a superfund by using a unique superfund ID",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "description": "Update properties on a single Superfund",
        "operationId": "updatesuperfund",
        "security": [
          {
            "OAuth2": [
              "payroll.superfunds"
            ]
          }
        ],
        "summary": "Updates a superfund",
        "tags": [
          "PayrollAu"
        ]
      }
    },
    "/transactions/{id}": {
      "get": {
        "operationId": "gettimesheets",
        "security": [
          {
            "OAuth2": [
              "payroll.timesheets.read"
            ]
          }
        ],
        "summary": "Retrieves timesheets",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "operationId": "createtimesheet-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.timesheets"
            ]
          }
        ],
        "summary": "Creates a timesheet",
        "tags": [
          "PayrollAu"
        ],
        "x-hasPayrollAuProblem": true
      }
    },
    "/timesheets/id": {
      "get": {
        "operationId": "gettimesheet",
        "security": [
          {
            "OAuth2": [
              "payroll.timesheets.read"
            ]
          }
        ],
        "summary": "Retrieves a timesheet by using a unique timesheet id",
        "tags": [
          "PayrollAu"
        ]
      },
      "post": {
        "description": "Update properties on a single timesheet",
        "operationId": "updatetimesheet-v2",
        "security": [
          {
            "OAuth2": [
              "payroll.timesheets"
            ]
          }
        ],
        "summary": "Updates a timesheet",
        "tags": [
          "PayrollAu"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "description": "For more information visit https://developer.xero.com/documentation/oauth2/overview",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
            "scopes": {
              "accounting.attachments": "Grant read-write access to attachments",
              "accounting.attachments.read": "Grant read-only access to attachments",
              "accounting.contacts": "Grant read-write access to contacts and contact groups",
              "accounting.contacts.read": "Grant read-only access to contacts and contact groups",
              "accounting.journals.read": "Grant read-only access to journals",
              "accounting.reports.read": "Grant read-only access to accounting reports",
              "accounting.settings": "Grant read-write access to organisation and account settings",
              "accounting.settings.read": "Grant read-only access to organisation and account settings",
              "accounting.transactions": "Grant read-write access to bank transactions, credit notes, invoices, repeating invoices",
              "accounting.transactions.read": "Grant read-only access to invoices",
              "assets assets.read": "Grant read-only access to fixed assets",
              "bankfeeds": "Grant read-write access to bankfeeds",
              "email": "Grant read-only access to your email",
              "files": "Grant read-write access to files and folders",
              "files.read": "Grant read-only access to files and folders",
              "openid": "Grant read-only access to your open id",
              "paymentservices": "Grant read-write access to payment services",
              "payroll": "Grant read-write access to payroll",
              "payroll.employees": "Grant read-write access to payroll employees",
              "payroll.employees.read": "Grant read-only access to payroll employees",
              "payroll.leaveapplications": "Grant read-write access to payroll leaveapplications",
              "payroll.leaveapplications.read": "Grant read-only access to payroll leaveapplications",
              "payroll.payitems": "Grant read-write access to payroll payitems",
              "payroll.payitems.read": "Grant read-only access to payroll payitems",
              "payroll.payrollcalendars": "Grant read-write access to payroll calendars",
              "payroll.payrollcalendars.read": "Grant read-only access to payroll calendars",
              "payroll.payruns": "Grant read-write access to payroll payruns",
              "payroll.payruns.read": "Grant read-only access to payroll payruns",
              "payroll.payslip": "Grant read-write access to payroll payslips",
              "payroll.payslip.read": "Grant read-only access to payroll payslips",
              "payroll.read": "Grant read-only access to payroll",
              "payroll.settings.read": "Grant read-only access to payroll settings",
              "payroll.superfundproducts.read": "Grant read-only access to payroll superfundproducts",
              "payroll.superfunds": "Grant read-write access to payroll superfunds",
              "payroll.superfunds.read": "Grant read-only access to payroll superfunds",
              "payroll.timesheets": "Grant read-write access to payroll timesheets",
              "payroll.timesheets.read": "Grant read-only access to payroll timesheets",
              "profile": "your profile information",
              "projects": "Grant read-write access to projects",
              "projects.read": "Grant read-only access to projects"
            },
            "tokenUrl": "https://identity.xero.com/connect/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}