{
  "openapi": "3.0.0",
  "servers": [
    {
      "description": "Xero Files API",
      "url": "https://api.xero.com/files.xro/1.0/"
    }
  ],
  "info": {
    "contact": {
      "email": "api@xero.com",
      "name": "Xero Platform Team",
      "url": "https://developer.xero.com",
      "x-twitter": "XeroAPI"
    },
    "description": "These endpoints are specific to Xero Files API",
    "termsOfService": "https://developer.xero.com/xero-developer-platform-terms-conditions/",
    "title": "Xero Files API",
    "version": "2.9.4",
    "x-apisguru-categories": [
      "financial"
    ],
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_files.yaml",
        "version": "3.0"
      }
    ],
    "x-providerName": "xero.com",
    "x-serviceName": "xero_files"
  },
  "tags": [
    {
      "description": "Operations available to regular developers",
      "name": "Files"
    }
  ],
  "paths": {
    "/associations/paymentid": {
      "get": {
        "description": "By passing in the appropriate options,",
        "operationId": "getassociationsbyobject-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves an association object using a unique object ID",
        "tags": [
          "Files"
        ]
      }
    },
    "/reviews/{id}": {
      "get": {
        "operationId": "getfiles-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves files",
        "tags": [
          "Files"
        ]
      },
      "post": {
        "operationId": "uploadfile-v2",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Uploads a File",
        "tags": [
          "Files"
        ]
      }
    },
    "/files/orderid": {
      "delete": {
        "description": "Delete a specific file",
        "operationId": "deletefile",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Deletes a specific file",
        "tags": [
          "Files"
        ]
      },
      "get": {
        "operationId": "getfile-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves a file by a unique file ID",
        "tags": [
          "Files"
        ]
      },
      "put": {
        "description": "Updates file properties of a single file",
        "operationId": "updatefile",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Update a file",
        "tags": [
          "Files"
        ]
      }
    },
    "/files/userid/associations": {
      "get": {
        "description": "By passing in the appropriate options, \n",
        "operationId": "getfileassociations",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves a specific file associations",
        "tags": [
          "Files"
        ]
      },
      "post": {
        "description": "By passing in the appropriate options, you can create a new folder",
        "operationId": "createfileassociation-v2",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Creates a new file association",
        "tags": [
          "Files"
        ]
      }
    },
    "/files/id/associations/sku": {
      "delete": {
        "description": "By passing in the appropriate options, you can create a new folder",
        "operationId": "deletefileassociation-v2",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Deletes an existing file association",
        "tags": [
          "Files"
        ]
      }
    },
    "/files/userid/content": {
      "get": {
        "description": "By passing in the appropriate options, retrieve data for specific file",
        "operationId": "getfilecontent-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves the content of a specific file",
        "tags": [
          "Files"
        ]
      }
    },
    "/inventory/{id}": {
      "get": {
        "description": "By passing in the appropriate options, you can search for available folders",
        "operationId": "getfolders-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves folders",
        "tags": [
          "Files"
        ]
      },
      "post": {
        "description": "By passing in the appropriate properties, you can create a new folder",
        "operationId": "createfolder-v2",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Creates a new folder",
        "tags": [
          "Files"
        ]
      }
    },
    "/folders/orderid": {
      "delete": {
        "description": "By passing in the appropriate ID, you can delete a folder",
        "operationId": "deletefolder",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Deletes a folder",
        "tags": [
          "Files"
        ]
      },
      "get": {
        "description": "By passing in the appropriate ID, you can search for specific folder",
        "operationId": "getfolder-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves specific folder by using a unique folder ID",
        "tags": [
          "Files"
        ]
      },
      "put": {
        "description": "By passing in the appropriate ID and properties, you can update a folder",
        "operationId": "updatefolder",
        "security": [
          {
            "OAuth2": [
              "files"
            ]
          }
        ],
        "summary": "Updates an existing folder",
        "tags": [
          "Files"
        ]
      }
    },
    "/profiles/{id}": {
      "get": {
        "description": "Search for the user inbox",
        "operationId": "getinbox-v2",
        "security": [
          {
            "OAuth2": [
              "files.read"
            ]
          }
        ],
        "summary": "Retrieves inbox folder",
        "tags": [
          "Files"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "description": "For more information",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.xero.com/identity/connect/authorize",
            "scopes": {
              "email": "Grant read-only access to your email",
              "files": "Grant read-write access to files and folders",
              "files.read": "Grant read-only access to files and folders",
              "openid": "Grant read-only access to your open id",
              "profile": "your profile information"
            },
            "tokenUrl": "https://identity.xero.com/connect/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}